INSERT INTO USERS (ID, USERNAME, PASSWORD) VALUES ('1', 'user1', 'password1');

INSERT INTO CURRENCIES (ID, NAME, SYMBOL) VALUES ('1', 'Tether', 'USDT');
INSERT INTO CURRENCIES (ID, NAME, SYMBOL) VALUES ('2', 'Ethereum', 'ETH');
INSERT INTO CURRENCIES (ID, NAME, SYMBOL) VALUES ('3', 'Bitcoin', 'BTC');

INSERT INTO ASSETS (CURRENCY_ID, USERS_ID, BALANCE) VALUES ('1', '1', '50000');
