CREATE TABLE USERS (
    ID INT PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE CURRENCIES (
    ID INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SYMBOL VARCHAR(50) NOT NULL
);

CREATE TABLE ASSETS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENCY_ID INT NOT NULL,
    USERS_ID INT NOT NULL,
    BALANCE NUMERIC DEFAULT 0,
    FOREIGN KEY (CURRENCY_ID) REFERENCES CURRENCIES(ID),
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
);

CREATE TABLE TRANSACTIONS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERS_ID INT NOT NULL,
    CURRENCY_PAIR INT NOT NULL,
    AMOUNT NUMERIC NOT NULL,
    TYPE VARCHAR(50) NOT NULL,
    PRICE NUMERIC NOT NULL,
    TOTAL NUMERIC NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    FOREIGN KEY (USERS_ID) REFERENCES USERS(ID)
);

CREATE TABLE PRICES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CURRENCY_PAIR INT NOT NULL,
    BID NUMERIC NOT NULL,
    ASK NUMERIC NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL
);